# Generated by Django 2.1.5 on 2020-10-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default="this is cool! I'm making incremental migrations based off of a model"),
        ),
    ]
